(*
   XCL - XDE's Component Library
   Copyright (C) 2005-2006 Judison Oliveira Gil Filho <judison@gmail.com>

   See the file COPYING.XCL, included in this distribution,
   for details about the copyright.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*)

{$I gtk_signals.inc}
{$I tcolormap.inc}
{$I tglist.inc}
{$I tgstrings.inc}
//--------------------- Actions / ActionLists / ActionLinks
{$I tactionlist.inc}
{$I tcontainedaction.inc}
{$I tcustomaction.inc}
{$I tactionlink.inc}
{$I tcontrolactionlink.inc}
//--------------------- Interfaces
{$I idesigner.inc}
//--------------------- Non Visual
{$I tclipboard.inc}
{$I tcanvas.inc}
{$I tpixbuf.inc}
{$I taccelgroup.inc}
{$I taccelerator.inc}
//---------------------
{$I tapplication.inc}
{$I tcontrol.inc}
{$I tmisccontrol.inc}
{$I tarrow.inc}
{$I tlabel.inc}
{$I timage.inc}
{$I tcontainercontrol.inc}
{$I tbincontrol.inc}
{$I tform.inc}
{$I tframe.inc}
{$I tcustombutton.inc}
{$I tcolorbutton.inc}
{$I tbutton.inc}
{$I ttogglebutton.inc}
{$I tcheckbutton.inc}
{$I tradiobutton.inc}
{$I tadjustment.inc}
{$I tscrolledwindow.inc}
{$I tnotebookpage.inc}
{$I thandlebox.inc}
{$I texpander.inc}
{$I tviewport.inc}
{$I tcustomtoolitem.inc}
{$I ttoolitem.inc}
{$I ttoolbutton.inc}
{$I tseparatortoolitem.inc}
{$I tpaned.inc}
{$I tfixed.inc}
{$I tmenubar.inc}
{$I tnotebook.inc}
{$I ttoolbar.inc}
{$I ttable.inc}
{$I tbox.inc}
{$I tbuttonbox.inc}
{$I tentry.inc}
{$I tspinbutton.inc}
{$I ttextview.inc}
{I tcombo.inc Deprecated}
{$I tcombobox.inc}
{$I tcustommenuitem.inc}
{$I tmenuitem.inc}
{$I tseparatormenuitem.inc}
{$I ttearoffmenuitem.inc}
{$I tprogressbar.inc}
{$I tstatusbar.inc}
{$I tcalendar.inc}
{$I tcolorselection.inc}
{$I tfilechooserwidget.inc}
{$I trange.inc}
{$I tscrollbar.inc}
{$I tscale.inc}
{$I tseparator.inc}
{$I ttimer.inc}
{$I ttextbuffer.inc}
{$I tdialog.inc}
{$I taboutdialog.inc}
{I tfileseldialog.inc Deprecated}
{$I tfilechooserdialog.inc}
// TreeView Itens (Arrumar ordem depois)
{$I ttreeviewcolumn.inc}
{$I ttreemodel.inc}
{$I ttreestore.inc}
{$I tliststore.inc}
{$I ttreeview.inc}
//--------------------- Utils
{$I util_quark.inc}
{$I util_color.inc}
{$I util_signals.inc}
{$I util_resources.inc}
