(*
   XCL - XDE's Component Library
   Copyright (C) 2005-2006 Judison Oliveira Gil Filho <judison@gmail.com>

   See the file COPYING.XCL, included in this distribution,
   for details about the copyright.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*)


//--------------------- Non Visual
{$I tfielddatalink.inc}
{$I tdatasetaction.inc}
//--------------------- Visual
{$I tdblabel.inc}
{$I tdbentry.inc}
