(*
   $Id: xcldb.inc,v 1.1 2005/12/30 17:21:38 judison Exp $

   XCL - XDE's Component Library
   Copyright (C) 2005 Judison Oliveira Gil Filho

   See the file COPYING.FPC, included in this distribution,
   for details about the copyright.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*)


//--------------------- Non Visual
{$I tfielddatalink.inc}
{$I tdatasetaction.inc}
//--------------------- Visual
{$I tdblabel.inc}
{$I tdbentry.inc}

{
$Log: xcldb.inc,v $
Revision 1.1  2005/12/30 17:21:38  judison
* Moved DB Comps to xcldb.inc
* Added TCanvas

}